feat: Rework claims methods
lidofinance/community-staking-module pull request #171
Opened 2024-05-09 14:16 UTC by dgusakov

2024-05-09 14:37 UTC, vgorkavenko submitted a review, later dismissed

2024-05-10 05:00 UTC, skhomuti requested changes

2024-05-10 07:07 UTC, dgusakov commented on src/abstract/CSBondCore.sol
> +    function _getClaimableBondShares(
Done

2024-05-10 07:10 UTC, skhomuti submitted a review, later dismissed

2024-05-10 08:18 UTC, vgorkavenko approved these changes

2024-05-10 08:24 UTC, skhomuti approved these changes

2024-05-10 08:24 UTC, merged