fix: `submitInitialSlashing` and `submitWithdrawal`
lidofinance/community-staking-module pull request #274
Opened 2024-07-11 08:36 UTC by vgorkavenko

2024-07-12 07:40 UTC, madlabman requested changes

2024-07-12 07:40 UTC, madlabman commented on src/CSModule.sol
> -
Return back the check.

2024-07-12 07:40 UTC, madlabman commented on src/CSModule.sol
>              accounting.resetBondCurve(nodeOperatorId);
Just `if (isSlashed) { accounting resetBondCurve; }`

2024-07-12 07:40 UTC, madlabman commented on src/CSModule.sol
> +                emit InitialSlashingSubmitted(nodeOperatorId, keyIndex);
It doesn't make sense to emit this event and to update the `_isValidatorSlashed` (we won't read it again). I think about something like `_isValidatorSlashed -> _initialSlashingSubmitted`. So we will have this exact case clearly separated.

2024-07-15 09:48 UTC, dgusakov approved these changes

2024-07-15 11:18 UTC, dgusakov approved these changes

2024-07-15 11:21 UTC, skhomuti approved these changes

2024-07-15 11:35 UTC, skhomuti approved these changes

2024-07-15 13:25 UTC, madlabman approved these changes

2024-07-15 14:14 UTC, merged