feat: Add CSBenefitsRegistry contract
lidofinance/community-staking-module pull request #374
Opened 2024-12-17 17:28 UTC by dgusakov

Only contract itself. No integration with CSModule

2025-01-08 14:21 UTC, vgorkavenko reviewed
⚠️ Didn't review `tests` ⚠️

2025-01-08 14:21 UTC, vgorkavenko commented on src/interfaces/ICSBenefitsRegistry.sol
> +    function getRewardShareData(
from offchain perspective would be useful to have smth like
```
function getRewardShareByKeysCount(
    uint256 curveId, uint256 keysCount
) external view returns (uint16 rewardSharesBP);
```
and the same for performance leeway

2025-01-08 14:21 UTC, vgorkavenko commented on src/CSBenefitsRegistry.sol
I'm not sure all you can put in here are benefits. There may also be limitations. It might touch narrative part.
Сan it be `CSPerksRegistry`?  or something similar

2025-01-08 14:21 UTC, vgorkavenko commented on src/interfaces/ICSBenefitsRegistry.sol
> +    /// @return limit Priority queue limit)
```suggestion
    /// @return limit Priority queue limit
```

2025-01-08 14:21 UTC, vgorkavenko commented on src/interfaces/ICSBenefitsRegistry.sol
> +    ///      100% rewards for the keys 1-10, 80% rewards fot the keys 11-50, and 50% rewards for the keys > 50
```suggestion
    ///      100% rewards for the keys 1-10, 80% rewards for the keys 11-50, and 50% rewards for the keys > 50
```
and below

2025-01-08 14:25 UTC, dgusakov commented on src/CSBenefitsRegistry.sol
> +
This is a good idea from the code perspective. However, it will limit the ability to add new perks later. So my take is not to implement it

2025-01-10 07:51 UTC, skhomuti requested changes

2025-01-10 07:51 UTC, skhomuti commented on src/interfaces/ICSPerksRegistry.sol
> +    /// @dev Default value is returned if the value is not set for the given curveId.
what does the default value means here
is it supposed to be a value from curve 0, or just zero value with means no priority queue

2025-01-10 12:50 UTC, dgusakov commented on src/CSPerksRegistry.sol
> +        }
Cause the number of pivots is N-1 where N is the number of values

2025-01-10 12:52 UTC, dgusakov commented on src/interfaces/ICSPerksRegistry.sol
> +    /// @dev Default value is returned if the value is not set for the given curveId.
Zero. Comment updated

2025-01-10 14:11 UTC, vgorkavenko commented on src/CSPerksRegistry.sol
> +        }
then `keysPivots[0] = 0` should be invalid value for setting

2025-01-13 08:36 UTC, skhomuti submitted a review, later dismissed

2025-01-13 09:42 UTC, dgusakov commented on src/CSPerksRegistry.sol
> +        }
Actually not. A case with no key pivots and a single value is valid.

2025-01-13 09:57 UTC, dgusakov commented on src/CSPerksRegistry.sol
> +        }
Fixed

2025-01-13 10:27 UTC, vgorkavenko approved these changes

2025-01-13 15:55 UTC, merged