Gates contracts
lidofinance/community-staking-module pull request #377
Opened 2024-12-23 12:03 UTC by skhomuti

2025-01-07 15:27 UTC, dgusakov requested changes
Reviewed partially without tests

2025-01-07 15:27 UTC, dgusakov commented on script/DeployImplementationsBase.s.sol
> +    address earlyAdoption;
Typo?

2025-01-07 15:27 UTC, dgusakov commented on script/DeployImplementationsBase.s.sol
> +            deployJson.set("VettedGate", address(vettedGate));
```suggestion
            deployJson.set("VettedGateImpl", address(vettedGate));
```

2025-01-07 15:27 UTC, dgusakov commented on script/DeployMainnet.s.sol
> +            .vettedGateTreeRoot = 0x359e02c5c065c682839661c9bdfaf38db472629bf5f7a7e8f0261b31dc9332c2; // See the first value in artifacts/mainnet/early-adoption/merkle-tree.json
We need to update the root before deployment to avoid double claming

2025-01-07 15:27 UTC, dgusakov commented on src/CSModule.sol
> +            _checkRole(CREATE_NODE_OPERATOR_ROLE);
For security reasons we can add a check for totalKeys == 0 to disallow uploading new keys to the exiting operators by gates

2025-01-10 11:39 UTC, skhomuti commented on script/DeployImplementationsBase.s.sol
> +    address earlyAdoption;
nope. it is an early adoption from v1

2025-01-10 11:40 UTC, skhomuti commented on script/DeployImplementationsBase.s.sol
> +                "PermissionlessGateImpl",
this is a typo indeed

2025-01-10 11:44 UTC, skhomuti commented on src/CSModule.sol
> +            : managementProperties.rewardAddress;
it was my 1st try, don't liked the result
a lot of boilerplate code in two contracts plus tests

2025-01-10 13:42 UTC, dgusakov commented on script/DeployMainnet.s.sol
> +            .vettedGateTreeRoot = 0x359e02c5c065c682839661c9bdfaf38db472629bf5f7a7e8f0261b31dc9332c2; // See the first value in artifacts/mainnet/early-adoption/merkle-tree.json
Add a comment pls

2025-01-10 15:56 UTC, vgorkavenko commented on script/DeployMainnet.s.sol
> +            .vettedGateTreeRoot = 0x359e02c5c065c682839661c9bdfaf38db472629bf5f7a7e8f0261b31dc9332c2; // See the first value in artifacts/mainnet/early-adoption/merkle-tree.json
there is room for frontrunning anyway. if somebody decides to claim EA before CSM plug-in the gate for v2

2025-01-10 15:56 UTC, vgorkavenko commented on src/CSModule.sol
> +    address internal _earlyAdoption;
shall we add a test for checking storage? just in case

2025-01-10 15:56 UTC, vgorkavenko commented on src/VettedGate.sol
> +        CURVE_ID = curveId;
can we check that the curve exists?

2025-01-10 15:56 UTC, vgorkavenko commented on src/abstract/CSBondCurve.sol
> -        if (curveId > $.bondCurves.length - 1) revert InvalidBondCurveId();
I think would be better to have `_curveExists(CSBondCurveStorage _storage)` to not to read the storage twice

2025-01-10 15:56 UTC, vgorkavenko commented on src/interfaces/ICSModule.sol
> +    /// @notice Permissioned method to add a new Node Operator
would add here role name that can call the method

2025-01-10 15:56 UTC, vgorkavenko commented on src/interfaces/ICSModule.sol
> +    /// @param from Sender address
```suggestion
    /// @param from tokens sender address
```

2025-01-10 15:56 UTC, vgorkavenko commented on src/interfaces/ICSModule.sol
> +    /// @param from Sender address
just to add a little more clarity

2025-01-10 16:09 UTC, skhomuti commented on src/CSModule.sol
> +    address internal _earlyAdoption;
what this test should test?

2025-01-10 16:11 UTC, vgorkavenko commented on src/CSModule.sol
> +    address internal _earlyAdoption;
That the storage won't corrupted after update

2025-01-10 16:19 UTC, skhomuti commented on src/interfaces/ICSModule.sol
> +    /// @notice Permissioned method to add a new Node Operator
we usually don't add the role name
added an explainer in the comment

2025-01-10 16:24 UTC, skhomuti commented on src/interfaces/ICSModule.sol
> +    /// @param from Sender address
added in other way

2025-01-17 08:28 UTC, dgusakov commented on script/DeployMainnet.s.sol
> +            .vettedGateTreeRoot = 0x359e02c5c065c682839661c9bdfaf38db472629bf5f7a7e8f0261b31dc9332c2; // See the first value in artifacts/mainnet/early-adoption/merkle-tree.json
We accept this risk as we already have duplicates (multiple addresses owned by a single person/entity) in the current list

2025-01-17 08:31 UTC, dgusakov commented on script/fork-helpers/SimulateVote.s.sol
> +        );
Why not an exact address here?

2025-01-17 08:32 UTC, dgusakov commented on script/fork-helpers/SimulateVote.s.sol
> +        csm.grantRole(csm.SET_BOND_CURVE_ROLE(), upgradeConfig.vettedGate);
We need to grant this role to the CSM committee as well

2025-01-17 08:32 UTC, dgusakov commented on src/CSAccounting.sol
> +    /// @dev Deprecated. Use setBondCurve with the corresponding role on the CSM contract instead
Can we remove it? This is not a storage, hence this is no longer needed

2025-01-17 08:34 UTC, dgusakov commented on src/CSModule.sol
> +        emit NodeOperatorAdded(
Should we add extendedManagerPermissions here?

2025-01-17 08:37 UTC, dgusakov commented on src/PermissionlessGate.sol
> +    ICSAccounting public immutable ACCOUNTING;
I can't see why we need it as immutable. It is only used in constructor

2025-01-17 14:31 UTC, skhomuti commented on script/fork-helpers/SimulateVote.s.sol
> +        csm.grantRole(csm.SET_BOND_CURVE_ROLE(), upgradeConfig.vettedGate);
in the deploy script as well
thanks, missed this

2025-01-20 06:00 UTC, skhomuti commented on script/fork-helpers/SimulateVote.s.sol
> +        );
to not overcomplicate the script for tests
this address is in the deploy scripts only, not in the configs

2025-01-20 06:02 UTC, skhomuti commented on src/CSModule.sol
> +        emit NodeOperatorAdded(
we can, but it adds a complexity for UIs, dashboards, etc
not sure yet we should

2025-01-20 06:03 UTC, skhomuti commented on src/PermissionlessGate.sol
> +    ICSAccounting public immutable ACCOUNTING;
oh right

2025-01-20 06:25 UTC, skhomuti commented on src/CSModule.sol
> +    address internal _earlyAdoption;
this would be a part of a separate upgrade tests I believe

2025-01-21 10:30 UTC, dgusakov commented on src/CSAccounting.sol
> +    /// @dev Deprecated. Use setBondCurve with the corresponding role on the CSM contract instead
Still relevant

2025-01-21 10:30 UTC, dgusakov commented on src/CSModule.sol
> +                .extendedManagerPermissions;
Maybe we can save some gas this way
```suggestion
            no.extendedManagerPermissions = true;
```

2025-01-21 10:30 UTC, dgusakov commented on src/VettedGate.sol
> +    uint256 public immutable CURVE_ID;
There are different orders here and in the permissionless gate

2025-01-21 13:50 UTC, dgusakov reviewed
Add integration tests for NO creation and curve claim via VettedGate

2025-01-21 13:50 UTC, dgusakov commented on test/CSAccounting.t.sol
Not sure if these changes are required

2025-01-21 13:50 UTC, dgusakov commented on test/VettedGate.t.sol
> +    function test_claimBondCurve_revertWhen_invalidRewardAddress() public {
```suggestion
    function test_claimBondCurve_revertWhen_notRewardAddress() public {
```

2025-01-21 13:50 UTC, dgusakov commented on test/VettedGate.t.sol
> +    function test_claimBondCurve_revertWhen_invalidManagerAddress() public {
```suggestion
    function test_claimBondCurve_revertWhen_notManagerAddress() public {
```

2025-01-21 13:50 UTC, dgusakov commented on test/fork/deployment/PostDeployment.t.sol
> +        assertEq(vettedGate.treeRoot(), deployParams.vettedGateTreeRoot);
Admin check?

2025-01-22 10:18 UTC, skhomuti commented on test/CSAccounting.t.sol
what exactly changes? there is no more role SET_BOND_CURVE_ROLE, so we need to change the tests

2025-01-22 10:20 UTC, skhomuti commented on src/CSAccounting.sol
> +    /// @dev Deprecated. Use setBondCurve with the corresponding role on the CSM contract instead
changed the code to not use it but forgot to remove, thx

2025-01-23 06:21 UTC, skhomuti commented on src/CSModule.sol
> +            if (_nodeOperators[nodeOperatorId].totalAddedKeys > 0) {
it is a part of the CreateNodeOperatorRole
this role cannot be used for uploading keys for existing node operators

2025-01-23 06:23 UTC, skhomuti commented on src/VettedGate.sol
> +    }
I believe we need it for a gate seal

2025-01-23 06:32 UTC, skhomuti commented on src/VettedGate.sol
> +        _consumedAddresses[member] = true;
oh good one
seems that no need of member arg here

2025-01-23 06:37 UTC, skhomuti commented on test/PermissionlessGate.t.sol
> +    function test_addNodeOperatorETH() public {
see integration tests in `CreateAndDeposit.sol`

2025-01-23 06:39 UTC, skhomuti commented on src/VettedGate.sol
> +    }
good one btw because forgot to add it to the gate seal

2025-01-23 15:40 UTC, dgusakov commented on src/CSModule.sol
> +            }
Yes, it should. To make NO management rules uniform

2025-01-23 15:44 UTC, dgusakov approved these changes

2025-01-23 21:47 UTC, madlabman commented on src/CSModule.sol
> +            no.rewardAddress
Silly question, maybe, but it looks like we read back from the storage, so can it be better to use  variables on the stack instead?

2025-01-23 21:47 UTC, madlabman commented on src/CSModule.sol
> +            if (_nodeOperators[nodeOperatorId].totalAddedKeys > 0) {
Agree with the @vgorkavenko here. Can we frame it like this:

```solidity
function _checkCanAddKeys(
    uint256 nodeOperatorId,
    address who
) internal view {
    // Most likely a direct call, so check the sender is a manager.
    if (who == msg.sender) {
        _onlyNodeOperatorManager(nodeOperatorId, msg.sender);
    } else {
        // We're trying to add keys via gate, check if we can do it.
        _checkRole(CREATE_NODE_OPERATOR_ROLE);
        if (_nodeOperators[nodeOperatorId].totalAddedKeys > 0) {
            revert NodeOperatorHasKeys();
        }
    }
}
 ```

2025-01-23 21:47 UTC, madlabman commented on src/VettedGate.sol
> +            : nodeOperator.rewardAddress;
Don't quite get why it's "rewardAddress" for a usual NO.

2025-01-23 21:47 UTC, madlabman commented on src/abstract/CSBondCurve.sol
> -        if (curveId > $.bondCurves.length - 1) revert InvalidBondCurveId();
I think `_getCSBondCurveStorage()` doesn't read from the storage, and just sets the slot value for the future access instead.

2025-01-24 07:06 UTC, skhomuti commented on src/CSModule.sol
> +            if (_nodeOperators[nodeOperatorId].totalAddedKeys > 0) {
like it

2025-01-24 07:16 UTC, skhomuti commented on src/VettedGate.sol
> +            : nodeOperator.rewardAddress;
allowing claim from manager address allows to transfer the manager to the "untrusted vetted address" in order to buy/sell other conditions in CSM

using reward address (or manager in case of extended permissions) makes it way more insecure -> reduce probability of happening

2025-01-24 08:16 UTC, skhomuti commented on src/CSModule.sol
> +            no.rewardAddress
it saves 300 gas

2025-01-24 08:33 UTC, skhomuti commented on src/abstract/CSBondCurve.sol
> -        if (curveId > $.bondCurves.length - 1) revert InvalidBondCurveId();
I think doesn't really mater, for me it's ok as well with private func as it is now

2025-01-24 09:14 UTC, madlabman approved these changes

2025-01-24 09:22 UTC, merged